module.exports = [
	{
		handle: '@pm_nepal',
		name: 'KP Sharma Oli',
		userWeight: 20,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@brb1954',
		name: 'Dr. Baburam Bhattarai',
		userWeight: 15,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@thapagk',
		name: 'Gagan Thapa',
		userWeight: 14,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@DeubaSherbdr',
		name: 'Sher Bahadur Deuba',
		userWeight: 12,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@RabindraMishra',
		name: 'Rabinda Mishra',
		userWeight: 10,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@SuryaRAcharya',
		name: 'Surya Raj Acharya',
		userWeight: 9,
		categoryWeight: 50,
		category: 'POLITICS',
	},
	{
		handle: '@buddhisagar',
		name: 'Buddi Sagar Bashyal',
		userWeight: 9,
		categoryWeight: 30,
		category: 'LITERATURE',
	},
	{
		handle: '@Vijaykumarko',
		name: 'Vijaya Kumar',
		userWeight: 20,
		categoryWeight: 40,
		category: 'JOURNALIST',
	},
	{
		handle: '@DahalTbd',
		name: 'Bhusan Dahal',
		userWeight: 19,
		categoryWeight: 40,
		category: 'JOURNALIST',
	},
	{
		handle: '@salokya',
		name: 'Salokya',
		userWeight: 15,
		categoryWeight: 40,
		category: 'JOURNALIST',
	},
	{
		handle: '@narayanwagle',
		name: 'Narayan Wagle',
		userWeight: 15,
		categoryWeight: 40,
		category: 'JOURNALIST',
	},
	{
		handle: '@KekiAdhikari',
		name: 'Keki Adhikari',
		userWeight: 15,
		categoryWeight: 20,
		category: 'ENTERTAINMENT',
	},
	{
		handle: '@IamSandeep25',
		name: 'Sandeep Lamichhane',
		userWeight: 20,
		categoryWeight: 45,
		category: 'SPORTS',
	},
	{
		handle: '@paras77',
		name: 'Paras Khada',
		userWeight: 19,
		categoryWeight: 45,
		category: 'SPORTS',
	},
]
